DROP TABLE t_nodes;
CREATE TABLE t_nodes (NEIGHBORHOOD_ID VARCHAR(75), NODE_NAME VARCHAR(75), PRIMARY_CONTACT VARCHAR(35), ADDRESS VARCHAR(65), PHONE VARCHAR(15), EMAIL VARCHAR(30), X_COORD VARCHAR(20), Y_COORD VARCHAR(20));
SELECT * FROM t_nodes